from .products import Product
from .category import Category
from .about import About
from .info import info
from .product1 import prices,Product1
from .customer import Customer
from .signup import Signup
from .authentication import Auth
from .volunteers import Volunteer
from .orders import Order
from .feedback import Feedback
from .institute import Institute
from .artisans import Artisans
from .Shipment import Shipment