# Generated by Django 3.2.4 on 2021-06-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(default='', upload_to='store/info'),
        ),
        migrations.AlterField(
            model_name='info',
            name='information',
            field=models.TextField(max_length=10000),
        ),
    ]
