# Generated by Django 3.2.4 on 2021-06-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_info_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricerange', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prices', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.prices')),
            ],
        ),
    ]
