# Generated by Django 3.2.4 on 2021-06-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_prices_product1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product1',
            old_name='prices',
            new_name='prices1',
        ),
    ]
