# Generated by Django 3.2.4 on 2021-06-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_prices_product1_prices1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/products1'),
        ),
        migrations.AddField(
            model_name='product1',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
