# Generated by Django 3.2.4 on 2021-06-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
