# Generated by Django 3.2.4 on 2021-06-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
