# Generated by Django 3.2.4 on 2021-06-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_customer_register_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='register_1',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
