# Generated by Django 3.2.4 on 2021-06-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_customer_register_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='register_1',
            field=models.CharField(default='', max_length=200),
        ),
    ]
