# Generated by Django 3.2.4 on 2021-06-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_customer_register_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=100000)),
                ('image', models.ImageField(default='', upload_to='store/info')),
            ],
        ),
    ]
