# Generated by Django 3.2.4 on 2021-06-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
