# Generated by Django 3.2.4 on 2021-07-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='address_optional',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='motive',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='re_enter',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
    ]
