# Generated by Django 3.2.4 on 2021-07-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210708_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='image',
        ),
    ]
