# Generated by Django 3.2.4 on 2021-08-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=15)),
                ('rating', models.CharField(default='', max_length=5)),
                ('experience', models.TextField(max_length=500)),
                ('improve', models.TextField(max_length=500)),
            ],
        ),
    ]
