# Generated by Django 3.2.4 on 2022-06-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_artisans_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisans',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
