# Generated by Django 3.2.4 on 2022-06-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_artisans_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artisans_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.artisans'),
        ),
        migrations.AddField(
            model_name='product1',
            name='artisans_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.artisans'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploads/artisans_product'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/artisans_product'),
        ),
    ]
