# Generated by Django 3.2.4 on 2022-06-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_order_artisans_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_status',
            new_name='order_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
