# Generated by Django 3.2.4 on 2022-06-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_auto_20220602_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='artisans_name',
        ),
        migrations.AddField(
            model_name='order',
            name='artisan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.artisans'),
        ),
    ]
