# Generated by Django 3.2.4 on 2022-06-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_auto_20220602_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='register_1',
        ),
    ]
