# Generated by Django 3.2.4 on 2022-06-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_remove_customer_register_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='artisan_id',
        ),
        migrations.AddField(
            model_name='order',
            name='artisan_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
