# Generated by Django 3.2.4 on 2022-06-03 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_auto_20220603_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=200)),
                ('tracking_id', models.CharField(default='', max_length=200)),
                ('company_contact', models.CharField(default='', max_length=200)),
                ('edd', models.DateTimeField(auto_now_add=True)),
                ('artisan_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.artisans')),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
    ]
