# Generated by Django 3.2.4 on 2022-06-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_order_artisan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='artisan_id',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='order',
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
